# Copyright 2025 Richard Kosegi
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
services:
  http:
    timeout: 30s
    cache:
      items: 10
      ttl: 15m
metricOpts:
  owm_current_humidity:
    desc: Current humidity
    labelsNames:
      - location
  owm_current_pressure:
    desc: Current atmospheric pressure
    labelsNames:
      - location
  owm_current_temperature:
    desc: Current temperature
    labelsNames:
      - location
  owm_current_temperature_feel:
    desc: Current temperature feel like
    labelsNames:
      - location
  owm_current_temperature_min:
    desc: Minimal currently observed temperature
    labelsNames:
      - location
  owm_current_temperature_max:
    desc: Maximal currently observed temperature
    labelsNames:
      - location
  owm_current_wind_direction:
    desc:
    labelsNames:
      - location
  owm_current_wind_speed:
    labelsNames:
      - location
  owm_exporter_api_requests:
    labelsNames:
      - location
  owm_exporter_scrapes_total:
    desc: Total number of times OWM was scraped for metrics.
    labelsNames:
      - location
targets:
  owm_vienna:
    vars:
      locationLabel: Vienna
      latitude: 48.20
      longitude: 16.37
      apiKey: 1123476946432654325
      pipeline:
        001-set:
          order: 1
          set:
            data:
              OWM_Mapping:
                - path: main.temp
                  metric: owm_current_temperature
                - path: main.feels_like
                  metric: owm_current_temperature_feel
                - path: main.temp_min
                  metric: owm_current_temperature_min
                - path: main.temp_max
                  metric: owm_current_temperature_max
                - path: main.pressure
                  metric: owm_current_pressure
                - path: main.humidity
                  metric: owm_current_humidity
                - path: wind.speed
                  metric: owm_current_wind_speed
                - path: wind.deg
                  metric: owm_current_wind_direction
        010-fetch:
          order: 10
          ext:
            func: http_fetch
            args:
              url: https://api.openweathermap.org/data/2.5/weather?lat={{ .vars.latitude }}&lon={{ .vars.longitude }}&units=metric&appid={{ .vars.apiKey}}
              headers:
                accept: application/json
              storeTo: Result.OWM.RAW
        011-parse:
          order: 11
          import:


        020-process:
          order: 20
          forEach:
            query: OWM_Mapping
            action:
              steps:
                01-check:
                  template:
                    template: |
                      TBD
