# Copyright 2025 Richard Kosegi
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
metrics:
  openmeteo_current_apparent_temperature:
    help: Current temperature feel like
    labels:
      - location
  openmeteo_current_cloud_cover:
    help: Total cloud cover as an area fraction
    labels:
      - location
  openmeteo_current_precipitation:
    help: Probability of precipitation
    labels:
      - location
  openmeteo_current_pressure_msl:
    help: Atmospheric air pressure reduced to mean sea level
    labels:
      - location
  openmeteo_current_rain:
    help: Rain from large scale weather systems
    labels:
      - location
  openmeteo_current_relative_humidity:
    help: Relative humidity
    labels:
      - location
  openmeteo_current_showers:
    help: Showers from convective precipitation
    labels:
      - location
  openmeteo_current_snowfall:
    help: Snowfall
    labels:
      - location
  openmeteo_current_surface_pressure:
    help: Atmospheric air pressure at surface
    labels:
      - location
  openmeteo_current_temperature:
    help: Current temperature
    labels:
      - location
  openmeteo_current_wind_dir:
    help: current wind direction
    labels:
      - location
  openmeteo_current_wind_gusts:
    help: Wind gusts at 10 meters above ground
    labels:
      - location
  openmeteo_current_wind_speed:
    help: Current wind speed.
    labels:
      - location
targets:
  openmeteo_vienna:
    steps:
      001-set:
        order: 1
        set:
          data:
            openmeteo:
              mapping:
                - path: current.apparent_temperature
                  metric: openmeteo_current_apparent_temperature
                - path: current.cloud_cover
                  metric: openmeteo_current_cloud_cover
                - path: current.precipitation
                  metric: openmeteo_current_precipitation
                - path: current.pressure_msl
                  metric: openmeteo_current_pressure_msl
                - path: current.rain
                  metric: openmeteo_current_rain
                - path: current.relative_humidity_2m
                  metric: openmeteo_current_relative_humidity
                - path: current.showers
                  metric: openmeteo_current_showers
                - path: current.snowfall
                  metric: openmeteo_current_snowfall
                - path: current.pressure_msl
                  metric: openmeteo_current_surface_pressure
                - path: current.temperature_2m
                  metric: openmeteo_current_temperature
                - path: current.wind_direction_10m
                  metric: openmeteo_current_wind_dir
                - path: current.wind_gusts_10m
                  metric: openmeteo_current_wind_gusts
                - path: current.wind_speed_10m
                  metric: openmeteo_current_wind_speed
      002-fetch:
        order: 2
        ext:
          function: http_fetch
          args:
            url: https://api.open-meteo.com/v1/forecast?latitude={{ .vars.latitude }}&longitude={{ .vars.longitude }}&current=temperature_2m,relative_humidity_2m,apparent_temperature,is_day,precipitation,rain,showers,snowfall,weather_code,cloud_cover,pressure_msl,surface_pressure,wind_speed_10m,wind_direction_10m,wind_gusts_10m
            headers:
              accept: application/json
            storeTo: openmeteo.Response
            parseJson: true
      003-process:
        order: 3
        forEach:
          query: openmeteo.mapping
          action:
            steps:
              01-set-metric:
                order: 1
                ext:
                  function: prom_gauge
                  args:
                    value: '{{ printf "{{ .openmeteo.Response.json.%s }}" .forEach.path }}'
                    ref: '{{ .forEach.metric }}'
                    labels:
                      - '{{ .vars.locationLabel }}'

vars:
  locationLabel: Vienna
  latitude: 48.20
  longitude: 16.37
